spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    drop-first: true
  datasource:
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console